# Numerical Computing with Python and Numpy

![](https://i.imgur.com/mg8O3kd.png)

This tutorial series is a beginner-friendly introduction to programming and data analysis using the Python programming language. These tutorials take a practical and coding-focused approach. The best way to learn the material is to execute the code and experiment with it yourself. 

## Working with numerical data

The "data" in *Data Analysis* typically refers to numerical data, e.g., stock prices, sales figures, sensor measurements, sports scores, database tables, etc. The [Numpy](https://numpy.org) library provides specialized data structures, functions, and other tools for numerical computing in Python. Let's work through an example to see why & how to use Numpy for working with numerical data.


> Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in  millimeters) & average relative humidity (in percentage) as a linear equation.
>
> `yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity`

We're expressing the yield of apples as a weighted sum of the temperature, rainfall, and humidity. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice.

Based on some statical analysis of historical data, we might come up with reasonable values for the weights `w1`, `w2`, and `w3`. Here's an example set of values:

Given some climate data for a region, we can now predict the yield of apples. Here's some sample data:

<img src="https://i.imgur.com/TXPBiqv.png" style="width:360px;">

To begin, we can define some variables to record climate data for a region.

In [37]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [38]:
kanto_temp = 73
kanto_rain = 67
kanto_humidity = 43

In [39]:
yeild_of_apple = w1*kanto_temp + w2*kanto_rain + w3*kanto_humidity

In [40]:
print(yeild_of_apple)

56.8


In [41]:
weights = [w1, w2, w3] # humare pass ek weight ka list hai or teen vectors hai regions k cool

In [42]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]

### ab ye manual krna har ek liye possible nahi hota hai, so we have to make a function 

In [43]:
result = 0
for x,y in zip(kanto, weights):
    result = result + x*y
print(result)

56.8


In [44]:
def yeild_of_apple(regions, weights):
    result = 0
    for x,y in zip(regions, weights):
        result = result + x*y
    return result



In [45]:
yeild_of_apple(kanto, weights)

56.8

In [46]:
yeild_of_apple(johto, weights)

76.9

In [47]:
import numpy as np # yaha pr hum alias de rahe hai isko numpy ko 

In [48]:
kanto = np.array([73, 67, 43])

In [49]:
kanto

array([73, 67, 43])

In [50]:
weights = np.array([w1, w2, w3])

In [51]:
weights

array([0.3, 0.2, 0.5])

In [52]:
type(weights)

numpy.ndarray

In [53]:
np.dot(kanto, weights) # ye function bilkul zip ke fucntion k equivalent hai

56.8

In [54]:
kanto

array([73, 67, 43])

In [55]:
array = weights * kanto # iska matalb point to point multiply krega array k ander NUMPY 

In [56]:
(kanto * weights).sum() # har ek ek elements ki multiply krega ye function seperately 

56.8

In [57]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])


In [58]:
climate_data.shape # ye mere pass ek matrix ki format mai agaya hai 

(5, 3)

In [59]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [60]:
arr3.shape

(2, 2, 3)

We can now compute the predicted yields of apples in all the regions, using a single matrix multiplication between `climate_data` (a 5x3 matrix) and `weights` (a vector of length 3). Here's what it looks like visually:

<img src="https://i.imgur.com/LJ2WKSI.png" width="240">

You can learn about matrices and matrix multiplication by watching the first 3-4 videos of this playlist: https://www.youtube.com/watch?v=xyAuNHPsq-g&list=PLFD0EB975BA0CC1E0&index=1 .

We can use the `np.matmul` function or the `@` operator to perform matrix multiplication.

In [61]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [62]:
# uper wale ka alternative ye hai @
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [63]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x15218a27cd0>)

In [64]:
# for reading the data 
climate_data=np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

### Yaha pr humne sabse pehle ek url ko download kiya uske baad humne yaha pr, usko retrieve kiya usko genfromtext se read kiya easily for the goal 


In [65]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [66]:
climate_data.shape # humne read krliya CSV ko bhaut jldi se 

(10000, 3)

In [67]:
weights = np.array([.3,.2,.5])

In [68]:
yeilds = climate_data @ weights

In [69]:
yeilds

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [70]:
yeilds=yeilds.reshape(10000,1)

In [71]:
# we will use the concatenate fucntion to add new column into the dataset 
np.concatenate((climate_data, yeilds)) # yaha pr error isiliye aaraha hai kyuki yaha pr axis missing hai why axis 0 hota hai row or axis 1 hota hai coulmns

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
climate_data.shape
yeilds.shape

(10000, 1)

In [72]:
climate_results = np.concatenate((climate_data, yeilds), axis =1)

In [77]:
np.savetxt('climate_results', climate_results, fmt='%.2f', header='Temp, rainfall, humidy, yeilds', comments='')

### Array Broadcasting

Numpy arrays also support *broadcasting*, allowing arithmetic operations between two arrays with different numbers of dimensions but compatible shapes. Let's look at an example to see how it works.

In [78]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [79]:
arr2.shape

(3, 4)

In [80]:
arr4 = np.array([4,5,6,7])

In [81]:
arr4.shape

(4,)

In [83]:
arr2 +arr4  # yaha array 2 k ander 4 add krdiya hai humne 

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [84]:
arr4 + arr2

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])